<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CustomerBusinessManagement.DataAccess\CustomerBusinessManagement.DataAccess.csproj" />
    <ProjectReference Include="..\CustomerBusinessManagement.DTO\CustomerBusinessManagement.DTO.csproj" />
  </ItemGroup>
</Project>
